//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;\
        ///    &lt;title&gt;@ViewBag.Title&lt;/title&gt;
        ///    &lt;script src=&quot;@Url.Content(&quot;~/Scripts/jquery-1.5.1.min.js&quot;)&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    @RenderBody()
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string mvc3AnotherLayout {
            get {
                return ResourceManager.GetString("mvc3AnotherLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @using System.Web.Mvc.Ajax
        ///@using System.Web.Mvc.Html
        ///@using System.Web.Mvc;
        ///@model IEnumerable&lt;Entities.AuditedOperation&gt;
        ///           &lt;script src=&quot;@Url.Content(&quot;~/Scripts/modernizr-1.7.min.js&quot;)&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///    &lt;tr&gt;
        ///        &lt;td class=&quot;sep_padding&quot;&gt;
        ///            &lt;table width=&quot;100%&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///                &lt;tr&gt;
        ///                    &lt;td class=&quot;section_tit&quot;&gt;
        ///                        U [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mvc3Child {
            get {
                return ResourceManager.GetString("mvc3Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;@ViewBag.Title&lt;/title&gt;
        ///    &lt;link href=&quot;@Url.Content(&quot;~/Content/Site.css&quot;)&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;&lt;script src=&quot;@Url.Content(&quot;~/Scripts/jquery-1.5.1.min.js&quot;)&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    @RenderBody()
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string mvc3DefaultLayout {
            get {
                return ResourceManager.GetString("mvc3DefaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    ViewBag.Title = &quot;ViewPage1&quot;;
        ///	Layout = &quot;~/Views/Shared/DefaultLayout.cshtml&quot;;
        ///	Layout = &quot;~/Views/Shared/AnotherLayout.cshtml&quot;;
        ///}
        ///&lt;link href=&quot;@Url.Content(&quot;~/Content/Site.css&quot;)&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///&lt;h2&gt;ViewPage1&lt;/h2&gt;.
        /// </summary>
        internal static string mvc3MultipleLayouts {
            get {
                return ResourceManager.GetString("mvc3MultipleLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;\
        ///    Layout = &quot;~/Views/Shared/AnotherLayout.cshtml&quot;;
        ///    &lt;title&gt;@ViewBag.Title&lt;/title&gt;
        ///    &lt;link href=&quot;@Url.Content(&quot;~/Content/Site.css&quot;)&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;script src=&quot;@Url.Content(&quot;~/Scripts/jquery-1.5.1.min.js&quot;)&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;@Url.Content(&quot;~/Scripts/modernizr-1.7.min.js&quot;)&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    @RenderBody()
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string mvc3PageWithAnotherLayout {
            get {
                return ResourceManager.GetString("mvc3PageWithAnotherLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    ViewBag.Title = &quot;TestViewPage&quot;;
        ///    Layout = &quot;~/Views/Shared/AnotherLayout.cshtml&quot;;
        ///}
        ///&lt;script src=&quot;@Url.Content(&quot;~/Scripts/modernizr-1.7.min.js&quot;)&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///&lt;h2&gt;@{Html.RenderPartial(&quot;Child&quot;)}&lt;/h2&gt;.
        /// </summary>
        internal static string mvc3PageWithChild {
            get {
                return ResourceManager.GetString("mvc3PageWithChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    Layout = &quot;~/Views/Shared/_Layout.cshtml&quot;;
        ///}.
        /// </summary>
        internal static string mvc3ViewStart {
            get {
                return ResourceManager.GetString("mvc3ViewStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{
        ///    ViewBag.Title = &quot;ViewPage1&quot;;
        ///}
        ///&lt;link href=&quot;@Url.Content(&quot;~/Content/Site.css&quot;)&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///&lt;h2&gt;ViewPage1&lt;/h2&gt;.
        /// </summary>
        internal static string mvc3WithDefaultLayout {
            get {
                return ResourceManager.GetString("mvc3WithDefaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls and stuff.
        /// </summary>
        internal static string webControl {
            get {
                return ResourceManager.GetString("webControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Page Title=&quot;Home Page&quot; Language=&quot;C#&quot; MasterPageFile=&quot;~/Site.master&quot; AutoEventWireup=&quot;true&quot;
        ///    CodeBehind=&quot;Default.aspx.cs&quot; Inherits=&quot;WebApplication1._Default&quot; %&gt;
        ///
        ///&lt;%@ Register src=&quot;WebUserControl1.ascx&quot; tagname=&quot;WebUserControl1&quot; tagprefix=&quot;uc1&quot; %&gt;
        ///
        ///&lt;asp:Content ID=&quot;HeaderContent&quot; runat=&quot;server&quot; ContentPlaceHolderID=&quot;HeadContent&quot;&gt;
        ///&lt;/asp:Content&gt;
        ///&lt;asp:Content ID=&quot;BodyContent&quot; runat=&quot;server&quot; ContentPlaceHolderID=&quot;MainContent&quot;&gt;
        ///    &lt;h2&gt;
        ///        Welcome to ASP.NET!
        ///
        ///
        ///    &lt;/h2&gt;
        ///    &lt;p&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webPage {
            get {
                return ResourceManager.GetString("webPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;%@ Master Language=&quot;C#&quot; AutoEventWireup=&quot;true&quot; CodeBehind=&quot;Site.master.cs&quot; Inherits=&quot;WebApplication1.SiteMaster&quot; %&gt;
        ///
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///&lt;head runat=&quot;server&quot;&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&quot;~/Styles/Site.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;script src=&quot;Scripts/jquery-1.4.1-vsdoc.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;Scripts [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string webPageWithRefs {
            get {
                return ResourceManager.GetString("webPageWithRefs", resourceCulture);
            }
        }
    }
}
